In [1]:
# 예제 1
symbols = "$*&!@"
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


In [2]:
# 예제 2
symbols = "$*&!@"

codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]


In [4]:
# 예제 3
x = '"!~$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [5]:
# 예제 4
symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [9]:
# 예제 5
symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c>64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord, symbols)}")
print(f"List after map:\n>>> {list(map(ord, symbols))}")

[126] 

Map function:
>>> <map object at 0x7a84ee8e2ef0>
List after map:
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


In [10]:
# 예제 6
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
    for size in sizes:
        print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [11]:
# 예제 7 제너레이터표현식에서 튜플 초기화하기
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [12]:
# 예제 7 제너레이터 표현식에서 배열 초기화하기
import array

ord_s = array.array('I', (ord(symbol) for symbol in symbols))

print(ord_s)

array('I', [33, 35, 94, 38, 38, 35])


In [13]:
# 예제 8
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirts in ('{} {}'.format(c, s) for s in sizes for c in colors):
    print(tshirts)

black S
white S
black M
white M
black L
white L


In [14]:
# 예제 9
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'),
                ('BRA', 'CE342567'),
                ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)
    print('{}/{}'.format(passport[0], passport[1]))
    print(f'{passport[0]}/{passport[1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


In [15]:
# 예제 10
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [16]:
# 예제 11
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
print(latitude)
print(longitude)

33.9425
-118.408056


In [17]:
# 예제 12
a = 10; b = 20
b, a = a, b
print(a, b)

20 10


In [18]:
# 예제 13
divmod(20, 8)

(2, 4)

In [19]:
# 예제 13
t = (20, 8)
divmod(*t)

(2, 4)

In [22]:
# 예제 13
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [25]:
# 예제 1４
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [29]:
# 예제 15
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [30]:
# 예제 15
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [31]:
# 예제 15
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [32]:
# 예제 16
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [33]:
# 예제 16
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [34]:
# 예제 17
metro_areas = [
    ("Tokyo", "JP", 36.933, (35, 139)),
    ("Delhi NCR", "IN", 21, (28, 77)),
    ("Mexico City", "MX", 20, (19, -99)),
    ("New York-Newark", "US", 20, (40, -74)),
    ("Sao Paulo", "BR", 19, (-23, -46)),
]

# Formatting the header
print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

# Unpacking the nested tuple and printing cities with longitude <= 0
for name, cc, pop, (lat, longi) in metro_areas:
    if longi <= 0:
        print(fmt.format(name, lat, longi))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [35]:
# 예제 1８
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139.691))

In [36]:
# 예제 １８
tokyo.population

36.933

In [37]:
# 예제 1８
tokyo.coordinates

(35.689, 139.691)

In [39]:
# 예제 1８
tokyo[1]

'JP'

In [44]:
# 예제 19
City._fields

('name', 'country', 'population', 'coordinates')

In [51]:
# 예제 19
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))

In [49]:
# 예제 19
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613, long=77.208)}

In [52]:
# 예제 19
for key, value in delhi._asdict().items():
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [53]:
# 예제 ２０
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [55]:
# 예제 ２０
l[2:]

[30, 40, 50, 60]

In [56]:
# 예제 ２０
l[:3]

[10, 20, 30]

In [57]:
# 예제 ２０
l[3:]

[40, 50, 60]

In [58]:
# 예제 21
invoice = """
0.....6................25.......33.......40........
1909   Pimoroni         $17.50    3      $52.50
1489   6mm Tactile      $4.95     2      $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

17.50     Pimoroni         $
4.95      6mm Tactile      $
 


In [59]:
# 예제 2２
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
# 예제 2２
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [61]:
# 예제 2２
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [62]:
# 예제 2２
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [63]:
# 예제 2３
l[2:5] = 100

TypeError: can only assign an iterable

In [64]:
# 예제 2４
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [65]:
# 예제 25
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [66]:
# 예제 25
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [67]:
# 예제 2６
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [68]:
# 예제 2６
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [71]:
# 예제 27
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [72]:
# 예제 27
weird_board[1][2] = 'O'
weird_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

In [74]:
# 예제 28
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)

board[1][2] = 'X'
board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [76]:
# 예제 29
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)

print(board)

board[2][0] = 'X'
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [81]:
# 예제 ３０
l = [1, 2, 3]
id(l)

134711358459072

In [78]:
# 예제 ３０
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [82]:
# 예제 ３０
id(l)

134711358459072

In [83]:
# 예제 31
t = (1, 2, 3)
id(t)

134711355524480

In [86]:
# 예제 31
t *= 2
id(t)

134711359232688

In [87]:
# 예제 3２
t = (1, 2, [30, 40])
print(t)

t[2] += [50, 60]

"""
a. t는 (1, 2, [30, 40, 50, 60])이 된다.
b. '튜플 객체는 항목 할당을 지원하지 않는다'는 메시지와 함께 TypeError가 발생한다.
c. a와 b 둘 다 틀리다.
d. a와 b 둘 다 맞다.
"""

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [88]:
# 예제 3３
print(t)

(1, 2, [30, 40, 50, 60])


In [89]:
# 예제 34
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [90]:
# 예제 34
fruits

['grape', 'raspberry', 'apple', 'banana']

In [91]:
# 예제 34
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [92]:
# 예제 34
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [93]:
# 예제 35
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [94]:
# 예제 35
fruits

['grape', 'raspberry', 'apple', 'banana']

In [95]:
# 예제 35
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [101]:
# 예제 36
from array import array
from random import random

floats = array('d', (random() for _ in range(10**7)))
floats[-1]

0.22178127632370004

In [102]:
# 예제 37
with open('floats.bin', 'wb') as f:
    floats.tofile(f)

floats2 = array('d')

with open('floats.bin', 'rb') as f:
    floats2.fromfile(f, 10**7)

floats2[-1]

0.22178127632370004

In [103]:
# 예제 37
floats == floats2

True

In [104]:
# 예제 3８
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [105]:
# 예제 3８
memv[0]

-2

In [106]:
# 예제 3８
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [107]:
# 예제 3８
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [108]:
# 예제 39
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [109]:
# 예제 39
type(a)

numpy.ndarray

In [111]:
# 예제 ４０
a.shape

(12,)

In [112]:
# 예제 ４０
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
# 예제 41
a[2]

array([ 8,  9, 10, 11])

In [115]:
# 예제 41
a[2, 1]

9

In [116]:
# 예제 41
a[:, 1]

array([1, 5, 9])

In [117]:
# 예제 42
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [132]:
# 예제 4３
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
# 예제 4３
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [134]:
# 예제 4３
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [135]:
# 예제 4４
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
# 예제 4４
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [137]:
# 예제 4４
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])